create Database D2;
use  D2;
Drop Database D2;

create Table STUDENT2 ( S_ID int primary key, S_Name Varchar(20), PhoneNO varchar(20), Email Varchar(30) );
drop table student2 ;

CREATE TABLE STUDENT3 ( S_ID INT PRIMARY KEY, SNAME VARCHAR (20), PH_NO INT , EMAIL VARCHAR(20)  );

INSERT INTO STUDENT3 ( S_ID,  SNAME, PH_NO,   EMAIL)  VALUES
(01, 'AAA', 11111111, 'AAA@GMAIL.COM'),
(02, 'BBB', 222222222, 'BBB@GMAIL.COM'),
(03, 'CCC', 3333333, 'CCC@GMAIL.COM'),
(04, 'DDD', 4444444, 'DDD@GMAIL.COM');
SELECT * FROM STUDENT3;

ALTER TABLE STUDENT3 ADD UNIQUE (SNAME);
ALTER TABLE STUDENT3 ADD UNIQUE (PH_NO); 

ALTER TABLE STUDENT3 ADD COLUMN (ADDRESS  VARCHAR(50)  );

SELECT * FROM STUDENT3;
DROP TABLE STUDENT2;
DROP TABLE STUDENT1;
DROP TABLE STUDENT ;

ALTER TABLE STUDENT3 CHANGE SNAME  S_NAME_NAME VARCHAR(255) ;

--  
USE DATABASE D2;
SELECT * FROM STUDENT3;



