USE D2;
SELECT * FROM STUDENT3;

--   ALTER COMMANDS -- 

ALTER TABLE STUDENT3  ADD COLUMN ADDRESS1 VARCHAR(250) DEFAULT 'AHMEDABAD' ;
ALTER TABLE STUDENT3 DROP COLUMN ADDRESS ;
ALTER TABLE STUDENT3 CHANGE COLUMN ADDRESS1 ADDRESS VARCHAR(500);
ALTER TABLE STUDENT3 RENAME ADDRESS TO ADDRESS2 VARCHAR(700) ;
-- ADD CONSTRAINTS

ALTER TABLE STUDENT3 ADD CONSTRAINT UNIQUE (S_ID);
ALTER TABLE STUDENT3 ADD COLUMN COURSE VARCHAR(50) NOT NULL;

-- UPDATE SET CASE 
UPDATE  STUDENT3
SET COURSE = 
      CASE S_ID
      WHEN 1 THEN 'B.E. ( COMP) '
	  WHEN 2 THEN 'B.SC. (MATHS)'
      ELSE ' B.COM'
	END ;
        
TRUNCATE TABLE STUDENT3;
SELECT * FROM STUDENT3;
ALTER TABLE STUDENT3 DROP COLUMN COURSE ;

UPDATE STUDENT3 
SET ADDRESS = 
   CASE S_ID
        WHEN 1 THEN 'A1A1A1A1'
        WHEN 2 THEN 'B2B2B2B2B2B2'
        WHEN 3 THEN 'C3C3C3C3C3C3'
        ELSE 'D4D4D4D4D4'
	END ;
    
INSERT INTO STUDENT3 VALUES
(5, 'EEE', 5555555, 'EEE&GMAIL.COM', 'E5E5E5E5' ) , 
(6, 'FFF', 6666666, 'FFF&GMAIL.COM', 'F6F6F6F6F' )  ;

SELECT * from STUDENT3 ;
-- DELETE
DELETE FROM STUDENT3 
WHERE S_ID= 6;


--    EMPLOYEE TABLE
CREATE DATABASE D3;
USE D3;
CREATE TABLE EMPLOYEES 
		( EMP_ID INT ,
          EMP_NAME VARCHAR(50)  ,
          DATE_OFJOINING VARCHAR (20),
          WORKING_HOURS INT ,
          EMP_SALARY INT  ) ;
          
          DROP TABLE EMPLOYEES ;
          
INSERT INTO EMPLOYEES  VALUES
(1, 'AMIT', '16-07-2023', 6 , 30000 ),          
(2, 'BOBBY', '16-07-2023', 8 , 50000),          
(3, 'CHINTAN ', '16-07-2023', 7 , 64000),          
(4, 'DAVID', '17-07-2023', 6 , 37000),          
(5, 'AMIT', '17-07-2023', 8 , 50000),          
(6, 'DAVID ', '17-07-2023', 7 , 60000),          
(7, 'GAYATRI', '18-07-2023', 6 , 30000),          
(8, 'HEERA', '18-07-2023', 8 , 85000),          
(9, 'BOBBY ', '18-07-2023', 7 , 45000);

SELECT * FROM EMPLOYEES ; 
truncate  EMPLOYEES;    

--  GROUP BY, HAVING CLAUSE, AGGREGATE FUNCTIONS
SELECT  SUM(WORKING_HOURS), SUM(EMP_SALARY) FROM EMPLOYEES GROUP BY DATE_OFJOINING ;


USE D3;

SELECT  MIN(WORKING_HOURS) FROM EMPLOYEES GROUP BY EMP_NAME;

ALTER TABLE EMPLOYEES CHANGE COLUMN DATE_OFJOINING WORKING_DATE VARCHAR(50) ;
ALTER TABLE EMPLOYEES ADD COLUMN EMP_DEPT VARCHAR(30);
ALTER TABLE EMPLOYEES ADD CONSTRAINT PRIMARY KEY(EMP_ID) ;

INSERT INTO EMPLOYEES  VALUES
(1, 'AMIT', '16-07-2023', 6 , 30000 , 'HR'),          
(2, 'BOBBY', '16-07-2023', 8 , 50000 , 'DEVELOPMENT'),          
(3, 'CHINTAN ', '16-07-2023', 7 , 64000, 'DEVELOPMENT'),          
(4, 'DAVID', '17-07-2023', 6 , 37000, ' TESTING'),          
(5, 'AMIT', '17-07-2023', 8 , 50000, 'DEVELOPMENT'),          
(6, 'DAVID ', '17-07-2023', 7 , 60000,  'DEVELOPMENT' ),          
(7, 'GAYATRI', '18-07-2023', 6 , 30000 , 'DESIGN' ),          
(8, 'HEERA', '18-07-2023', 8 , 85000 , ' MANAGEMENT'),          
(9, 'BOBBY ', '18-07-2023', 7 , 45000 ,  'DEVELOPMENT');

TRUNCATE EMPLOYEES ;
ALTER TABLE EMPLOYEES ADD constraint primary key ( EMP_ID) ;

SELECT * FROM EMPLOYEES;

SELECT EMP_DEPT, MAX( EMP_SALARY) FROM EMPLOYEES GROUP BY EMP_DEPT;

SELECT WORKING_HOURS, COUNT(EMP_DEPT) FROM EMPLOYEES GROUP BY WORKING_HOURS;
-- 

UPDATE EMPLOYEES 
SET WORKING_HOURS = 10 WHERE EMP_NAME ='DAVID' ;


UPDATE EMPLOYEES 
SET EMP_ID=100 WHERE EMP_DEPT = ' MANAGEMENT' ;


UPDATE EMPLOYEES 
SET WORKING_HOURS = 4 WHERE EMP_DEPT=' MANAGEMENT';
SELECT * FROM EMPLOYEES;
ALTER  TABLE EMPLOYEES CHANGE EMP_DEPT EMP_DEPARTMENT VARCHAR(30);
 
UPDATE EMPLOYEES  SET EMP_SALARY =
 CASE EMP_DEPARTMENT 
		WHEN ' MANAGEMENT' THEN 85000
        WHEN 'DEVELOPMENT'  THEN 45000
        WHEN ' TESTING' THEN 30000
        WHEN 'DESIGN' THEN 35000
         ELSE 25000        
	END;
        
update EMPLOYEES SET EMP_DEPARTMENT = 'TESTING' WHERE EMP_DEPARTMENT = ' TESTING' ; 

SELECT emp_department, max(working_hours) FROM EMPLOYEES GROUP BY EMP_DEPARTMENT ;
UPDATE EMPLOYEES SET WORKING_HOURS =
	CASE EMP_DEPARTMENT
		WHEN 'HR' THEN 7
        WHEN 'DEVELOPMENT' THEN 12
        WHEN 'DESIGN' THEN 8
        WHEN 'TESTING' THEN 6
        ELSE 4
	END;

select avg(emp_salary) from employees group by emp_department ;
select max(emp_salary) from employees group by emp_department ;
select min(emp_salary) from employees group by emp_department ;

ALTER TABLE EMPLOYEES  MODIFY column EMP_SALARY VARCHAR(10);


USE D3;
DROP TABLE WORKER;

UPDATE STUDENT3 SET SNAME = 'AMULYA' WHERE SNAME LIKE 'A%';
SELECT * FROM STUDENT3 ;
 UPDATE STUDENT3  SET SNAME =  'BHOOMI' WHERE SNAME LIKE 'B%' ;
UPDATE STUDENT3   SET SNAME = 'CHINTAN' WHERE SNAME LIKE 'C%' ;
UPDATE STUDENT3 SET SNAME = 'DAVID' WHERE SNAME LIKE 'd%' ;
UPDATE STUDENT3 SET SNAME = 'EESHAAN' WHERE SNAME LIKE 'E%' ;